# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
#org.gradle.jvmargs=
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Mod Info
mod_id=ldlib2
mod_name=LowDragLib2
mod_version=26.1.2.39
mod_description=Low Drag Lib2, a library for rendering, gui, particles, synchronize
mod_license=LGPL-3.0 license
mod_url=https://github.com/Low-Drag-MC/LDLib2
mod_authors=KilaBash
maven_group=com.lowdragmc.ldlib2
## Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=26.1.2
archives_name=ldlib2-neoforge-26.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[26.1, 26.1.2]
loader_version_range=[4,)
# Mappings
# https://lambdaurora.dev/tools/import_quilt.html
qm_version=5
#kotlin version
kotlin_stdlib_version=2.1.20
# NeoForge
# https://files.neoforged.neoforge.net/net/neoforged.neoforge/forge/
neo_version=26.1.2.100
neo_version_range=[26.1.0.8-beta,)
# JEI - https://modrinth.com/mod/jei/versions#all-versions
jei_version=29.34.0.90
jei_version_range=[29.34.0.90,)
# REI - https://modrinth.com/mod/rei/versions#all-versions
rei_version=16.0.799
# KJS - https://modrinth.com/mod/kubejs/versions#all-versions
kjs_version=2100.7.0-build.117
# EMI - https://modrinth.com/mod/emi/versions
emi_version=1.1.22+1.21.1
# AE2 - https://modrinth.com/mod/ae2/versions
ae2_version=19.2.17
yoga_version=1.0.0
taffy_version=1.1.4
# Iris - https://modrinth.com/mod/iris
iris_version=1.8.12+1.21.1-neoforge
# sodium - https://modrinth.com/mod/sodium/version/mc1.21.1-0.6.13-neoforge
sodium_version=mc1.21.1-0.6.13-neoforge
# moddevmcp
moddevmcp_version=0.3



kotlin.jvm.target.validation.mode=ignore



